"""empty message

Revision ID: 78698c451ef6
Revises: 
Create Date: 2020-05-14 00:39:56.005383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78698c451ef6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_created_at'), 'broker', ['created_at'], unique=False)
    op.create_index(op.f('ix_broker_name'), 'broker', ['name'], unique=True)
    op.create_index(op.f('ix_broker_updated_at'), 'broker', ['updated_at'], unique=False)
    op.create_index(op.f('ix_broker_uuid'), 'broker', ['uuid'], unique=True)
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_name'), 'exchange', ['name'], unique=True)
    op.create_index(op.f('ix_exchange_uuid'), 'exchange', ['uuid'], unique=True)
    op.create_table('trade_account_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_account_type_type'), 'trade_account_type', ['type'], unique=True)
    op.create_index(op.f('ix_trade_account_type_uuid'), 'trade_account_type', ['uuid'], unique=True)
    op.create_table('trade_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_position_position'), 'trade_position', ['position'], unique=True)
    op.create_index(op.f('ix_trade_position_uuid'), 'trade_position', ['uuid'], unique=True)
    op.create_table('trade_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_status_status'), 'trade_status', ['status'], unique=True)
    op.create_index(op.f('ix_trade_status_uuid'), 'trade_status', ['uuid'], unique=True)
    op.create_table('trade_strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_strategy_created_at'), 'trade_strategy', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_strategy_description'), 'trade_strategy', ['description'], unique=True)
    op.create_index(op.f('ix_trade_strategy_name'), 'trade_strategy', ['name'], unique=True)
    op.create_index(op.f('ix_trade_strategy_updated_at'), 'trade_strategy', ['updated_at'], unique=False)
    op.create_index(op.f('ix_trade_strategy_uuid'), 'trade_strategy', ['uuid'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('ticker', sa.String(length=4), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_full_name'), 'security', ['full_name'], unique=True)
    op.create_index(op.f('ix_security_ticker'), 'security', ['ticker'], unique=True)
    op.create_index(op.f('ix_security_uuid'), 'security', ['uuid'], unique=True)
    op.create_table('trade_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('account_type_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['trade_account_type.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_account_created_at'), 'trade_account', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_account_name'), 'trade_account', ['name'], unique=True)
    op.create_index(op.f('ix_trade_account_updated_at'), 'trade_account', ['updated_at'], unique=False)
    op.create_index(op.f('ix_trade_account_uuid'), 'trade_account', ['uuid'], unique=True)
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['trade_account.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['trade_position.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['trade_status.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['trade_strategy.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_created_at'), 'trade', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_entry_timestamp'), 'trade', ['entry_timestamp'], unique=False)
    op.create_index(op.f('ix_trade_exit_timestamp'), 'trade', ['exit_timestamp'], unique=False)
    op.create_index(op.f('ix_trade_updated_at'), 'trade', ['updated_at'], unique=False)
    op.create_index(op.f('ix_trade_uuid'), 'trade', ['uuid'], unique=True)
    op.create_table('trade_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_note_created_at'), 'trade_note', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_note_updated_at'), 'trade_note', ['updated_at'], unique=False)
    op.create_index(op.f('ix_trade_note_uuid'), 'trade_note', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_note_uuid'), table_name='trade_note')
    op.drop_index(op.f('ix_trade_note_updated_at'), table_name='trade_note')
    op.drop_index(op.f('ix_trade_note_created_at'), table_name='trade_note')
    op.drop_table('trade_note')
    op.drop_index(op.f('ix_trade_uuid'), table_name='trade')
    op.drop_index(op.f('ix_trade_updated_at'), table_name='trade')
    op.drop_index(op.f('ix_trade_exit_timestamp'), table_name='trade')
    op.drop_index(op.f('ix_trade_entry_timestamp'), table_name='trade')
    op.drop_index(op.f('ix_trade_created_at'), table_name='trade')
    op.drop_table('trade')
    op.drop_index(op.f('ix_trade_account_uuid'), table_name='trade_account')
    op.drop_index(op.f('ix_trade_account_updated_at'), table_name='trade_account')
    op.drop_index(op.f('ix_trade_account_name'), table_name='trade_account')
    op.drop_index(op.f('ix_trade_account_created_at'), table_name='trade_account')
    op.drop_table('trade_account')
    op.drop_index(op.f('ix_security_uuid'), table_name='security')
    op.drop_index(op.f('ix_security_ticker'), table_name='security')
    op.drop_index(op.f('ix_security_full_name'), table_name='security')
    op.drop_table('security')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_trade_strategy_uuid'), table_name='trade_strategy')
    op.drop_index(op.f('ix_trade_strategy_updated_at'), table_name='trade_strategy')
    op.drop_index(op.f('ix_trade_strategy_name'), table_name='trade_strategy')
    op.drop_index(op.f('ix_trade_strategy_description'), table_name='trade_strategy')
    op.drop_index(op.f('ix_trade_strategy_created_at'), table_name='trade_strategy')
    op.drop_table('trade_strategy')
    op.drop_index(op.f('ix_trade_status_uuid'), table_name='trade_status')
    op.drop_index(op.f('ix_trade_status_status'), table_name='trade_status')
    op.drop_table('trade_status')
    op.drop_index(op.f('ix_trade_position_uuid'), table_name='trade_position')
    op.drop_index(op.f('ix_trade_position_position'), table_name='trade_position')
    op.drop_table('trade_position')
    op.drop_index(op.f('ix_trade_account_type_uuid'), table_name='trade_account_type')
    op.drop_index(op.f('ix_trade_account_type_type'), table_name='trade_account_type')
    op.drop_table('trade_account_type')
    op.drop_index(op.f('ix_exchange_uuid'), table_name='exchange')
    op.drop_index(op.f('ix_exchange_name'), table_name='exchange')
    op.drop_table('exchange')
    op.drop_index(op.f('ix_broker_uuid'), table_name='broker')
    op.drop_index(op.f('ix_broker_updated_at'), table_name='broker')
    op.drop_index(op.f('ix_broker_name'), table_name='broker')
    op.drop_index(op.f('ix_broker_created_at'), table_name='broker')
    op.drop_table('broker')
    # ### end Alembic commands ###
